const generateUserName = () => {
  const adjetivoAleatorio =
    adjetivos[Math.floor(Math.random() * adjetivos.length)];
  const sustantivoAleatorio =
    sustantivos[Math.floor(Math.random() * sustantivos.length)];
  const userName = `${sustantivoAleatorio}${adjetivoAleatorio}`;
  return userName;
};

  const adjetivos = [    "Divertido",    "Brillante",    "Audaz",    "Encantador",    "Gracioso",    "Creativo",    "Aventurero",    "Curioso",    "Juguetón",    "Fantástico",    "Travieso",    "Risueño",    "Amable",    "Genial",    "Astuto",    "Elegante",    "Exuberante",    "Saltarín",    "Intrépido",    "Fascinante",    "Impredecible",    "Bromista",    "Luminoso",    "Veloz",    "Encantado",    "Soñador",    "Chispeante",    "Animado",    "Intrigante",    "Risueño",    "Deslumbrante",    "Exótico",    "Magnífico",    "Asombroso",    "Escurridizo",    "Alocado",    "Ocurrente",    "Rebelde",    "Vibrante",    "Ingenioso",    "Apasionado",    "Encantador",    "Ardiente",    "Enérgico",    "Sorprendente",    "Encantador",    "Fascinante",    "Lúdico",    "Festivo",    "Divino",    "Cautivador",    "Delicioso",    "Emocionante",    "Irresistible",    "Jubiloso",    "Misterioso",    "Original",    "Radiante",    "Espléndido",    "Único",    "Versátil",    "Zen",    "Exquisito",    "Fabuloso",    "Inspirador",    "Tentador",    "Vital",    "Maravilloso",    "Singular",    "Sobresaliente",    "Extraordinario",    "Deslumbrante",    "Fascinante",    "Asombroso",    "Fantástico",    "Estupendo",    "Asombroso",    "Sensacional",    "Espectacular",    "Increíble",    "Magnífico",    "Brillante",    "Fantástico",    "Impresionante",    "Sobresaliente",    "Sensacional",    "Espléndido",    "Maravilloso",    "Genial",    "Increíble",    "Estupendo",    "Sorprendente",    "Increíble",    "Espectacular",    "Fabuloso",    "Sensacional",    "Sorprendente",    "Genial",    "Asombroso",    "Extraordinario"  ];
  
  const sustantivos = [    "Unicornio",    "Cerebro",    "Cohete",    "Sirena",    "Dragón",    "Ninja",    "Héroe",    "Pirata",    "Tornado",    "Fantasma",    "Bruja",    "Viajero",    "Explorador",    "Superhéroe",    "Estrella",    "Aventurero",    "Tesoro",    "Volcán",    "Cascada",    "Tormenta",    "Tigre",    "León",    "Elefante",    "Jaguar",    "Pantera",    "Serpiente",    "Lobo",    "Oso",    "Zorro",    "Águila",    "Lince",    "Gato",    "Perro",    "Rana",    "Delfín",    "Ballena",    "Tiburón",    "Pez",    "Pulpo",    "Calamar",    "Medusa",    "Caracol",    "Mariposa",    "Abeja",    "Hormiga",    "Araña",    "Escorpión",    "Ciervo",    "Oso",    "Cebra",    "Jirafa",    "Rinoceronte",    "Cocodrilo",    "Hipopótamo",    "Gorila",    "Chimpancé",    "Orangután",    "Koala",    "Panda",    "Canguro",    "Pingüino",    "Flamenco",    "Pavo",    "Águila",    "Búho",    "Cóndor",    "Halcón",    "Loro",    "Guacamayo",    "Picaflor",    "Colibrí",    "Albatros",    "Gaviota",    "Paloma",    "Garza",    "Martín pescador",    "Flamenco",    "Avestruz",    "Aardvark",    "Armadillo",    "Bisonte",    "Dromedario",    "Búfalo",    "Chinchilla",    "Tejón",    "Gorila",    "Hiena",    "Iguana",    "Lémur",    "Marmota",    "Narval",    "Ñandú",    "Orangután",    "Ocelote",    "Quokka",    "Ualabí",    "Zorro",    "Zarigüeya",    "Yaguareté",    "Colibrí"  ];
  
module.exports = { generateUserName };
